#!/bin/csh -f
#
# Update this Matlab Library with some more recent version.
# This script should be run in the directory to be updated.
#
# Note that the trailing slash in the source directory name
# is needed for correct behaviour.
#
# Examples:
# libsync -n ../newer_lib/
# libsync -n mevans@remotehost:matlab/lib/

echo rsync -aruv --exclude "*~" --exclude "*.mat" $* ./
rsync -aruv --exclude "*~" --exclude "*.mat" $* ./
